# Generated by Django 4.2.5 on 2023-09-29 23:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
