# Generated by Django 4.2.5 on 2023-09-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_video_video_audio_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
