# Generated by Django 4.2.5 on 2023-10-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_audio',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='session_id',
            field=models.CharField(default='1', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_path',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
